Scripts and data update
eastgenomics/QC_Classifier pull request #2
Opened 2023-08-29 15:34 UTC by Arun-bioinformatics

modified:   CEN_multiqc_config_v2.1.0.yaml
- New key added inside table_cond_formatting_rules to test records that is only found in read data

**new file:**   idUniqueIdRelationship.json
- Essential file to describe relationship between IDs found in config.yaml and multiqc.json

**new file:**   mypackage/functions.py
- Functions for QC classifier project

**new file:**   codeInfo.py
- Non essential python script which explains the applications of functions from mypackage

**new file:**   fullAssembly.py
- Script which unifies functions from mypackage to ouput potential .json

**new file:** CEN_multiqc_config_v2.1.0.yaml
- Included config file that will be used as example for the QC classifier project.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/QC_Classifier/2)

2023-08-31 09:08 UTC, jethror1 requested changes
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/qc_classifier/2)* status: 1 of 6 files reviewed, 28 unresolved discussions (waiting on @Arun-bioinformatics)

___
*[`CEN_multiqc_config_v2.1.0.yaml` line 1 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd5yWSN3xYRdcsnyG3S:-Nd5yWSN3xYRdcsnyG3T:b-e876l9) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/CEN_multiqc_config_v2.1.0.yaml#L1)):*
> ```YAML
> ###################################################
> ```

not sure if this file needs to be included, unless you want to keep it in a test data dir or similar?
___
*[`codeInfo.py` line 1 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd5yfUh3qzFjOd5e4QO:-Nd5yfUh3qzFjOd5e4QP:b-wlgklm) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/codeInfo.py#L1)):*
> ```Python
> import mypackage.functions as Classifier
> ```

is this just for your own notes? if so can you remove it (or I'd add it in a markdown file or something called `notes.md` or something to make it clear its not a real script)
___
*[`fullAssembly.py` line 2 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd62W-C1cZQJFKSB_SO:-Nd62W-C1cZQJFKSB_SP:bbeppyf) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/fullAssembly.py#L2)):*
> ```Python
> import mypackage.functions as Classifier
> from ruamel.yaml import YAML
> ```

any reason for using this YAML parser? afaik pyyaml is the most widely used / oldest (and should just be in the standard library): https://pypi.org/project/PyYAML/



_Code quote:_
```Python
from ruamel.yaml import YAML
```
___
*[`fullAssembly.py` line 3 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd5zBh83NXzClN1D7Z7:-Nd5zBh83NXzClN1D7Z8:b5t5mig) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/fullAssembly.py#L3)):*
> ```Python
> import mypackage.functions as Classifier
> from ruamel.yaml import YAML
> import json
> ```

convention for ordering imports is alphanumerically following the order:
1.  standard library imports
2.  related third party imports
3.  local application/library specific imports

i.e. for yours:
```
import json

from ruamel.yaml import YAML

import mypackage.functions as Classifier
```

a linter such as pylint enabled in vscode should highlight this for you, here's an example with a load of imports: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/master/resources/home/dnanexus/generate_workbook/utils/excel.py#L1



_Code quote:_
```Python
import mypackage.functions as Classifier
from ruamel.yaml import YAML
import json
```
___
*[`fullAssembly.py` line 26 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd5ym0U-hzgQhJ0uxnm:-Nd5ym0U-hzgQhJ0uxnn:b-xnsaku) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/fullAssembly.py#L26)):*
> ```Python
> 
> 
> '''
> ```

if this is going to stay as a file docstring it should be at the top above the imports



_Code quote:_
```Python
'''
We have all the functions needed to generate the individual
outputs that wee need, all we have to do is join everything together in
a complex dictionary.

All inputs:
    - idUniqueIDRelationship.json
    - multiqc_data.json
    - .yaml file

Output:
We will add more complexity as we go through it but starting with the following
    {"record":["sample_ids":{"Value":1.0, "Status":"pass"}]}

Next step of complexity
    {"thresholds": parameters, "record":["sample_ids":{"Value":1.0, "Status":"pass"}]}

Future next step of complexity
    {Header_ID: {"thresholds": parameters, "record":["sample_ids":{"Value":1.0, "Status":"pass"}]}}


'''
```
___
*[`fullAssembly.py` line 29 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd61CjoCI1oRPvQ13o2:-Nd61CjoCI1oRPvQ13o3:bvapl0f) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/fullAssembly.py#L29)):*
> ```Python
> 
> # List of samples
> multiqc_data = json.load(open("multiqc_data.json"))
> ```

reading a file like this with `open()` will leave an open pointer to the file and keep it open, the better way to read from files is:
```
with open(some_file) as f:
    data = json.load(f)
```

when the file has been read in and drops out of the `with` statement it will automatically close the file



_Code quote:_
```Python
multiqc_data = json.load(open("multiqc_data.json"))
```
___
*[`fullAssembly.py` line 32 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd9oJyA7CgGyfJhtbpS:-Nd9oJyB1j7nNpbe_EPP:b-wxf9qa) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/fullAssembly.py#L32)):*
> ```Python
> sample_lists = Classifier.getSampleLists(multiqc_data)
> 
> # List of uniqueIDs
> ```

are these unique_ids the ids of fields we have set in the config? if so calling it 'config_fields' might be clearer, as when you're dealing with samples using ID gets confusing



_Code quote:_
```Python
# List of uniqueIDs
```
___
*[`fullAssembly.py` line 35 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd9pBuD7epKDAG2QsVV:-Nd9pBuD7epKDAG2QsVW:b-2p3o5i) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/fullAssembly.py#L35)):*
> ```Python
> yaml_file = "CEN_multiqc_config_v2.1.0.yaml"
> with open(yaml_file,'r') as file:
>     yaml_content = YAML().load(file)
> ```

I would have this as its own `read_config()` function in a utils file or similar and call it, example of similar: https://github.com/eastgenomics/optimised_filtering/blob/main/utils/file_utils.py



_Code quote:_
```Python
yaml_file = "CEN_multiqc_config_v2.1.0.yaml"
with open(yaml_file,'r') as file:
    yaml_content = YAML().load(file)
```
___
*[`fullAssembly.py` line 52 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd9onA6CA4m3fbQAk-e:-Nd9onA74kLZVwOQ7Ex9:b-xvu0t9) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/fullAssembly.py#L52)):*
> ```Python
>         record_structure = None
> 
>         parameters = Classifier.getUniqueParameters(uniqueID, "CEN_multiqc_config_v2.1.0.yaml")
> ```

 I assume the config wants to be an input to the script and not hardcoded, I'd recommend looking at parse_args if you haven't before, here's a couple of examples :
- https://github.com/eastgenomics/optimised_filtering/blob/1b75fe42abe0f5733eeff4da70087af3c7d13797/add_optimised_filtering.py#L11
- https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/4b914db6963b179b31bc28f93b24c7c889b6445f/resources/home/dnanexus/generate_workbook/generate_workbook.py#L64 



_Code quote:_
```Python
"CEN_multiqc_config_v2.1.0.yaml"
```
___
*[`fullAssembly.py` line 58 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd9oazB3NI5WDfQGiO5:-Nd9oazB3NI5WDfQGiO6:b-jjfhsz) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/fullAssembly.py#L58)):*
> ```Python
>         # Parameters values are around the 100s
>         # Whereas associated values are around 1.0-0.9s
>         if uniqueID == 'mqc-generalstats-picard-PCT_TARGET_BASES_20X':
> ```

is this the only field where this happens?



_Code quote:_
```Python
'mqc-generalstats-picard-PCT_TARGET_BASES_20X':
```
___
*[`fullAssembly.py` line 72 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd9o6qCBzvUjRB-Pe_d:-Nd9o6qCBzvUjRB-Pe_e:bb7phvt) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/fullAssembly.py#L72)):*
> ```Python
>             record_structure = []
> 
>             # If value found, then retrieve value and status for all  [...]

2023-09-05 12:00 UTC, Arun-bioinformatics reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/qc_classifier/2)* status: 0 of 7 files reviewed, 26 unresolved discussions (waiting on @jethror1)

___
*[`fullAssembly.py` line 2 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd62W-C1cZQJFKSB_SO:-NdGSgoEDlcmPahmdEAr:b-59dpow) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/fullAssembly.py#L2)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

any reason for using this YAML parser? afaik pyyaml is the most widely used / oldest (and should just be in the standard library): https://pypi.org/project/PyYAML/
</blockquote></details>

Cool, now I am using PyYAML version 6.0.1
___
*[`fullAssembly.py` line 3 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd5zBh83NXzClN1D7Z7:-NdUc-Sk9XZM1zhQ0-B5:b-3j0b44) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/fullAssembly.py#L3)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

convention for ordering imports is alphanumerically following the order:
1.  standard library imports
2.  related third party imports
3.  local application/library specific imports

i.e. for yours:
```
import json

from ruamel.yaml import YAML

import mypackage.functions as Classifier
```

a linter such as pylint enabled in vscode should highlight this for you, here's an example with a load of imports: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/master/resources/home/dnanexus/generate_workbook/utils/excel.py#L1
</blockquote></details>

The order of imports was modified to the following:

```
import json
import yaml
import mypackage.functions as Classifier
```
___
*[`fullAssembly.py` line 26 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd5ym0U-hzgQhJ0uxnm:-NdUcHOw5LzO_jrBwPAr:b-896fix) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/fullAssembly.py#L26)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

if this is going to stay as a file docstring it should be at the top above the imports
</blockquote></details>

Done.
___
*[`fullAssembly.py` line 29 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd61CjoCI1oRPvQ13o2:-NdUq3KJEjEK8nuv4FSQ:b-896fix) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/fullAssembly.py#L29)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

reading a file like this with `open()` will leave an open pointer to the file and keep it open, the better way to read from files is:
```
with open(some_file) as f:
    data = json.load(f)
```

when the file has been read in and drops out of the `with` statement it will automatically close the file
</blockquote></details>

Done.
___
*[`fullAssembly.py` line 32 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd9oJyA7CgGyfJhtbpS:-NdUrQBt0d181b5D52ma:b-896fix) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/fullAssembly.py#L32)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

are these unique_ids the ids of fields we have set in the config? if so calling it 'config_fields' might be clearer, as when you're dealing with samples using ID gets confusing
</blockquote></details>

Done.
___
*[`fullAssembly.py` line 35 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd9pBuD7epKDAG2QsVV:-NdUtySK1Go8tMEjCQSx:b-896fix) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/fullAssembly.py#L35)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I would have this as its own `read_config()` function in a utils file or similar and call it, example of similar: https://github.com/eastgenomics/optimised_filtering/blob/main/utils/file_utils.py
</blockquote></details>

Done.
___
*[`fullAssembly.py` line 58 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd9oazB3NI5WDfQGiO5:-NdUy9FZEThr8oi8WRA6:b-x738vw) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/fullAssembly.py#L58)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this the only field where this happens?
</blockquote></details>

Yes, I am not sure of how to code it in a better way, but I am open to new suggestions.
___
*[`fullAssembly.py` line 72 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd9o6qCBzvUjRB-Pe_d:-NdV383-Bd48t_-PR1YN:bvm7z8d) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/fullAssembly.py#L72)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Resolved
___
*[`codeInfo.py` line 1 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd5yfUh3qzFjOd5e4QO:-NdGNqvWBU2CVpVaQ7Oh:b-zb7077) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/codeInfo.py#L1)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this just for your own notes? if so can you remove it (or I'd add it in a markdown file or something called `notes.md` or something to make it clear its not a real script)
</blockquote></details>

This will now be added onto a `notes.md` file
___
*[`CEN_multiqc_config_v2.1.0.yaml` line 1 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd5yWSN3xYRdcsnyG3S:-NdG45MEClzL766z5Gs3:b3ehwen) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/CEN_multiqc_config_v2.1.0.yaml#L1)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

not sure if this file needs to be included, unless you want to keep it in a test data dir or similar?
</blockquote></details>

Would want to keep it in a test_files directory, since current Python scripts are getting built while using the config file. Will be removed in the future.
___
*[`mypackage/functions.py` line 3 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd60o2s-bi0Qe1JQcmu:-NdV3Zyw32eolbn3o5c2:b-896fix) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/mypackage/functions.py#L3)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

import ordering as above
</blockquote></details>

Done.
___
*[`mypackage/functions.py` line 4 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd60Xwa4es-5LgroqTb:-NdV3c7s2SnF5V-uclyd:b-896fix) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/mypackage/functions.py#L4)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I would recommend renaming this file to something more descriptive like `utils.py`, and probably the directory either as `bin/` or `utils/`
</blockquote></details>

Done.
___
*[`mypackage/functions.py` line 6 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd62uDH8x7WNsj4fDu1:-NdG9RZt4KKogl2w2kPs:be6wks8) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/mypackage/functions.py#L6)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

function naming should follow camel case: i.e. `def get_header_id()`
</blockquote></details>

Will change all functions to the same format like `def map_header_id()`, but wouldn't that be called snake  [...]

2023-09-05 13:25 UTC, jethror1 requested changes
> Reviewed 5 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/qc_classifier/2)* status: 5 of 7 files reviewed, 9 unresolved discussions (waiting on @Arun-bioinformatics)

___
*[`fullAssembly.py` line 58 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd9oazB3NI5WDfQGiO5:-Nd_T2Mw7oOde8iPZq1A:bd7l74p) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/fullAssembly.py#L58)):*
<details><summary><i>Previously, Arun-bioinformatics (Arun Karnani Khemlani) wrote…</i></summary><blockquote>

Yes, I am not sure of how to code it in a better way, but I am open to new suggestions.
</blockquote></details>

nope no real issue, just if there were going to be more I'd change it but this is sensible
___
*[`bin/utils.py` line 24 at r3](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd_TPQDCMJm84yZ3Lrs:-Nd_TPQDCMJm84yZ3Lrt:b-e7p4g) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ebd119db2aa43713a0a76e8dd33bafb179b72546/bin/utils.py#L24)):*
> ```Python
>     """
>     # First get file from resources/ folder
>     with open("gitRepo/QC_Classifier/resources/idUniqueIdRelationship.json",
> ```

personally if you're doing paths relative to your script (i.e in a different directory but in the same code base, I would use something like `pathlib` as its more robust, and reference the relative folder, should be something like this:
```
from pathlib import Path

Path(__file__).parent.joinpath('../resources/idUniqueIdRelationship.json')
```

docs for pathlib are pretty good too and let you write code that will work on linux and windows: https://docs.python.org/3/library/pathlib.html



_Code quote:_
```Python
gitRepo/QC_Classifier/resources/idUniqueIdRelationship.json
```
___
*[`mypackage/functions.py` line 6 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd62uDH8x7WNsj4fDu1:-Nd_TBsJElkJLlJ_fGor:b8wmwzm) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/mypackage/functions.py#L6)):*
<details><summary><i>Previously, Arun-bioinformatics (Arun Karnani Khemlani) wrote…</i></summary><blockquote>

Will change all functions to the same format like `def map_header_id()`, but wouldn't that be called snake case?
</blockquote></details>

yep sorry, end of day brain not working


<!-- Sent from Reviewable.io -->

2023-09-05 13:57 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/qc_classifier/2)* status: 5 of 7 files reviewed, 10 unresolved discussions (waiting on @Arun-bioinformatics)

___
*[`fullAssembly.py` line 3 at r2](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd_cYj45lNKWAS0tznQ:-Nd_cYj45lNKWAS0tznR:bb7phvt) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/d4eed60745b0c23e682ff1a2d73fc3aecb0cacd5/fullAssembly.py#L3)):*
> ```Python
> """
> We have all the functions needed to generate the individual 
> outputs that wee need, all we have to do is join everything together in
> ```

typo



_Code quote:_
```Python
wee
```


<!-- Sent from Reviewable.io -->

2023-09-05 15:38 UTC, Arun-bioinformatics reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/qc_classifier/2)* status: 5 of 8 files reviewed, 9 unresolved discussions (waiting on @jethror1)

___
*[`fullAssembly.py` line 52 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd9onA6CA4m3fbQAk-e:-Nd_icOHCZKP-xBcnYn7:b-my89n3) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/fullAssembly.py#L52)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I assume the config wants to be an input to the script and not hardcoded, I'd recommend looking at parse_args if you haven't before, here's a couple of examples :
- https://github.com/eastgenomics/optimised_filtering/blob/1b75fe42abe0f5733eeff4da70087af3c7d13797/add_optimised_filtering.py#L11
- https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/4b914db6963b179b31bc28f93b24c7c889b6445f/resources/home/dnanexus/generate_workbook/generate_workbook.py#L64
</blockquote></details>

Included argparse module to parse the multiqc_data.json and config.yaml
___
*[`fullAssembly.py` line 58 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd9oazB3NI5WDfQGiO5:-Nd_dTCO8H5Jw8jfQcEw:b-896fix) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/fullAssembly.py#L58)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

nope no real issue, just if there were going to be more I'd change it but this is sensible
</blockquote></details>

Done.
___
*[`fullAssembly.py` line 3 at r2](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd_cYj45lNKWAS0tznQ:-Nd_dFzH3mk8JRpxG64Z:bb6un1j) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/d4eed60745b0c23e682ff1a2d73fc3aecb0cacd5/fullAssembly.py#L3)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done
___
*[`bin/utils.py` line 24 at r3](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd_TPQDCMJm84yZ3Lrs:-Nd_jQ5FAzmu6IyQ9Pdk:b1mw53) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ebd119db2aa43713a0a76e8dd33bafb179b72546/bin/utils.py#L24)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

personally if you're doing paths relative to your script (i.e in a different directory but in the same code base, I would use something like `pathlib` as its more robust, and reference the relative folder, should be something like this:
```
from pathlib import Path

Path(__file__).parent.joinpath('../resources/idUniqueIdRelationship.json')
```

docs for pathlib are pretty good too and let you write code that will work on linux and windows: https://docs.python.org/3/library/pathlib.html
</blockquote></details>

Thank you! that is really helpful to know.
___
*[`mypackage/functions.py` line 6 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd62uDH8x7WNsj4fDu1:-Nd_dZv151ViSyJwkWo8:b-896fix) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/mypackage/functions.py#L6)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

yep sorry, end of day brain not working
</blockquote></details>

Done.
___
*[`mypackage/functions.py` line 119 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd9l5l18Vji3HrLjMPj:-Nd_uZQQ7gkDCs5Dv_3O:bx67f66) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/mypackage/functions.py#L119)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

so here are you only returning data for happy for controls and then everything else for the other samples? again need to think about controls not just being RD/happy
</blockquote></details>

Need to discuss about it in person


<!-- Sent from Reviewable.io -->

2023-09-07 13:41 UTC, Arun-bioinformatics reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/qc_classifier/2)* status: 5 of 10 files reviewed, 9 unresolved discussions (waiting on @jethror1)

___
*[`fullAssembly.py` line 89 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd9nJHA6QQbaixjEaFv:-NdjnABH0WU92aBvX8tx:b-896fix) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/fullAssembly.py#L89)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

convention here if this is your main entrypoint script is to format it like this and not to have code 'bare' outside of functions, as this will make everything in the global scope which is not the best, here's an example: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/4b914db6963b179b31bc28f93b24c7c889b6445f/resources/home/dnanexus/generate_workbook/generate_workbook.py#L511

if its a tiny script with not much 'main' logic then it can be fine to put everything under the `if __name__ == "__main__":` statement, but I generally like to chuck it all in a `main()` function for readability
</blockquote></details>

Done.
___
*[`mypackage/functions.py` line 48 at r1](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-Nd68KYdAYzStFNTBu5o:-Nddh7dnDCqj_RdpYdv2:brm5ab8) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ef6521e29db2692ddceff55635e2baeb3b413282/mypackage/functions.py#L48)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I would consider using the samplesheet as an input to use as truth for getting the sample IDs from instead of trying to parse from the report sections since the samplesheet is the truth source for samplenames on a run, here's a function you can steal to parse it: https://github.com/eastgenomics/eggd_conductor/blob/262d9abcd20bf141a92d9f59fe3498cfe48d0dc7/resources/home/dnanexus/run_workflows/run_workflows.py#L29
</blockquote></details>

Spoke to Matt about this, and he seems to agree.

Take for example one sample with sampleID '123991777-23187R0015-23NGCEN9-9527-F-99347387', this ID would be found in a tuple like so:

('123991777-23187R0015-23NGCEN9-9527-F-99347387', <---- right here
('123991777-23187R0015-23NGCEN9-9527-F-99347387_S2_L001_R2',
'123991777-23187R0015-23NGCEN9-9527-F-99347387_S2_L002_R1',
'123991777-23187R0015-23NGCEN9-9527-F-99347387_S2_L002_R2',
'123991777-23187R0015-23NGCEN9-9527-F-99347387_S2_L001_R1'))

SampleSheet.csv does include Sample IDs, but it not include read IDs (like '123991777-23187R0015-23NGCEN9-9527-F-99347387_S2_L001_R2').  So will get read IDs from multiqc_data.json file, open to other suggestions.


<!-- Sent from Reviewable.io -->

2023-09-07 15:24 UTC, jethror1 requested changes
> Reviewed 1 of 3 files at r4, 2 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/qc_classifier/2)* status: 8 of 10 files reviewed, 5 unresolved discussions (waiting on @Arun-bioinformatics)

___
*[`full_assembly.py` line 40 at r5](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-NdkC56kEiuDoQN0YhnO:-NdkC56kEiuDoQN0YhnP:b-siglec) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ccd8c66bc9ff29ccf0ffac4ff4079f07eaf56f5f/full_assembly.py#L40)):*
> ```Python
>                     help='filepath to config.yaml file')
> 
> args = parser.parse_args()
> ```

please can this be in its own function too please and not global



_Code quote:_
```Python
parser = argparse.ArgumentParser(description='QC Classifier for multiqc data')
parser.add_argument('samplesheet', type=str,
                    help='Filepath to SampleSheet.csv file')
parser.add_argument('data', type=str,
                    help='filepath to multiqc.json file')
parser.add_argument('config', type=str,
                    help='filepath to config.yaml file')

args = parser.parse_args()
```
___
*[`full_assembly.py` line 51 at r5](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-NdkBwj_42MEdj3yE9-B:-NdkBwj_42MEdj3yE9-C:b5tl1gy) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ccd8c66bc9ff29ccf0ffac4ff4079f07eaf56f5f/full_assembly.py#L51)):*
> ```Python
> YAML_FILE = args.config
> yaml_content = Classifier.read_config(YAML_FILE)
> config_fields = list(yaml_content["table_cond_formatting_rules"].keys())
> ```

can all of this go into `main()` or separate functions for loading files



_Code quote:_
```Python
args = parser.parse_args()
# List of samples
sample_sheet = args.samplesheet
MULTIQC_DATA_FILE = args.data
with open(MULTIQC_DATA_FILE, 'r', encoding='UTF-8') as file:
    multiqc_data = json.load(file)
sample_lists = Classifier.get_sample_lists(multiqc_data, sample_sheet)

# List of config_fields
YAML_FILE = args.config
yaml_content = Classifier.read_config(YAML_FILE)
config_fields = list(yaml_content["table_cond_formatting_rules"].keys())
```


<!-- Sent from Reviewable.io -->

2023-09-12 09:52 UTC, jethror1 reviewed
> Reviewed 2 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/qc_classifier/2)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @Arun-bioinformatics)



<!-- Sent from Reviewable.io -->

2023-09-12 10:55 UTC, Arun-bioinformatics reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/qc_classifier/2)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`full_assembly.py` line 40 at r5](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-NdkC56kEiuDoQN0YhnO:-Ne80xoJ7jsILUw6J1sw:b-uheco7) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ccd8c66bc9ff29ccf0ffac4ff4079f07eaf56f5f/full_assembly.py#L40)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

please can this be in its own function too please and not global
</blockquote></details>

Done, implemented in latest branch
___
*[`full_assembly.py` line 51 at r5](https://reviewable.io/reviews/eastgenomics/qc_classifier/2#-NdkBwj_42MEdj3yE9-B:-Ne810PSBvS0xGYPEBpp:b-lkw74b) ([raw file](https://github.com/eastgenomics/qc_classifier/blob/ccd8c66bc9ff29ccf0ffac4ff4079f07eaf56f5f/full_assembly.py#L51)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can all of this go into `main()` or separate functions for loading files
</blockquote></details>

Done, implemented in latest branch.


<!-- Sent from Reviewable.io -->

2023-09-12 11:26 UTC, jethror1 approved these changes
> Reviewed 1 of 1 files at r6, 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/qc_classifier/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Arun-bioinformatics)



<!-- Sent from Reviewable.io -->

2023-09-12 11:26 UTC, merged